sudo: required

services:
  - docker

install:
  - docker build -t monstereos/frontend ./services/demux 
  - docker build -t monstereos/frontend ./services/frontend

script:
  - docker run monstereos/demux yarn lint
  - docker run monstereos/frontend yarn lint
